### ISSUE TITLE
Binary "disappered"

### ISSUE THREAD

**Issue by Zykino** [codota/tabnine-atom#13]
I got the following message on each keystroke:

![image](https://user-images.githubusercontent.com/3809938/77933677-5cccf280-72af-11ea-879a-0a5cc51c370b.png)

I found that the binary is in the `x86_64-unknown-linux-musl` subfolder instead of `x86_64-unknown-linux-gnu`.

So I did:
```sh
$ mkdir .atom/packages/TabNine/binaries/2.5.1/x86_64-unknown-linux-gnu
$ cd .atom/packages/TabNine/binaries/2.5.1/x86_64-unknown-linux-gnu
$ ln -s ../x86_64-unknown-linux-musl/TabNine
```

And now TabNine looks to work correctly. (At least `TabNine::version` show me the binary version.)

**Comment by dimacodota** [comment]
released in 2.5.2 version
