### ISSUE TITLE
TabNine no longer works with atom

### ISSUE THREAD

**Issue by jwaggy** [codota/tabnine-atom#18]
![image](https://user-images.githubusercontent.com/24530821/79405115-8d748380-7f61-11ea-83a5-6b1bbfb133a1.png)

This is my current settings page after the last update. I can't disable or uninstall it.

**Comment by dimacodota** [comment]
hey @jwaggy, what os are you using? Can you open the configuration (TabNine :: config)? If so, can you please attach the logs (located at the bottom of the page)? 
Thanks

**Comment by jwaggy** [comment]
Windows 10 Pro

Nothing comes up. I'm not sure if I am missing something or if somehow somewhere a configuration file was corrupted but I can't find the reason and this is the only thing affected.

**Comment by dimacodota** [comment]
could you please try to reinstall it by following these steps:

1. go to Packages -> Settings View -> Open 
2. click the "Open Config Folder" button 
3. in the config folder under the "packages" folder delete the "TabNine" folder 
4. reinstall TabNine from the install Packages

<img width="1792" alt="Screen Shot 2020-04-17 at 22 37 03" src="https://user-images.githubusercontent.com/60742964/79607604-263f0680-80fc-11ea-9efd-aabd64e6e629.png">


Thanks

**Comment by jwaggy** [comment]
That seems to have fixed it. Thanks.

**Comment by mmusgrave** [comment]
Following that process did not fix the issue for me. 

I cannot get `Tabnine::config` to do anything
