### ISSUE TITLE
Cant uninstall TabNine extension after newest update broke the package

### ISSUE THREAD

**Issue by AlikanakelaKarwowski** [codota/tabnine-atom#29]
Title

Trying to click uninstall, through atoms package manager is futile. its spins for a second then stops and says "Cant Uninstall ..." and the uninstall button goes back to being normal.

Was working earlier today, went to update it, then tabnine stopped working all together. Went to uninstall and reinstall and now I cant uninstall. I can only disable it.

Windows 10

**Comment by DemoorBug** [comment]
https://github.com/codota/tabnine-atom/issues/18#issuecomment-615429725

**Comment by akhilsplendid** [comment]
![image_2021-07-20_052652](https://user-images.githubusercontent.com/68068908/126242002-c886552c-5d3b-4028-bfac-0a508763292a.png)
I don't know what the issue is?
