### ISSUE TITLE
Defer to autocomplete-snippets when appropriate

### ISSUE THREAD

**Issue by csvoss** [codota/tabnine-atom#3]
I have a snippet set up using the built-in Atom package `autocomplete-snippets` to insert an `import ipdb; ipdb.set_trace()` (a Python debugger trace) into my code whenever I type `p` `d` `b` `tab`. However, TabNine is overriding my snippet behavior, making me unable to insert the ipdb snippet.

This is blocking me from keeping TabNine enabled because I need some workflow for dropping in debugger traces using few keystrokes.

(Naturally, debugger traces are nowhere to be found in my codebase that TabNine is indexing, so TabNine has not itself learned the syntax for inserting a debugger trace, otherwise I'd happily defer to TabNine's suggestions in order to achieve few keystrokes.)

**Comment by douglas** [comment]
Same case for me - I use a lot of `binding.pry` but autocomplete with tabnine does not see the available snippets, which is a deal breaker for me.

**Comment by KNWR** [comment]
Echoing Chelsea's point, I'd love to see this :) Otherwise makes it difficult to use tab9

**Comment by Zireael** [comment]
TabNine suppresses all other snippet providers.
Please add option to customise max number of suggestions Provided by TabNine and allow showing other snippet provider results.
Your functionality is decent, but it's not 'be all end all'.
