### ISSUE TITLE
Tabnine not worjing

### ISSUE THREAD

**Issue by jaro17** [codota/tabnine-atom#43]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**

win 10
1.54.0 x64
Error: connect ECONNREFUSED 127.0.0.1:53459
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)

**Comment by jaro17** [comment]
win 10
1.54.0 x64
Error: connect ECONNREFUSED 127.0.0.1:53459
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)

**Comment by boaz-codota** [comment]
Hey @jaro17 ,

Did you close the issue because you managed to resolve the issue? Or do you need further help?
