### ISSUE TITLE
Suppressing Atom built-in snippets for Latex

### ISSUE THREAD

**Issue by fangzhou-xie** [codota/tabnine-atom#8]
I just found this awesome plugin (especially with new deep learning features). I disabled several plugins (Kite and autocomplete-python) but found out that when writing latex documents, built-in plugins (like snippets) are disabled. Those features in latex came back after disabling TabNine and re-enabling autocomplete-python (yes, I dunno why a python plugin affects latex behavior!). I wonder if TabNine automatically disables build-in packages from working? Is there a solution to this problem I am facing? 

Thank you for providing this awesome package by the way!

**Comment by zxqfl** [comment]
TabNine doesn't explicitly suppress other plugins, but since it registers itself as available for all languages it can sometimes cause other plugins to not be selected.

I'll leave this issue open and add a setting to control this at some point in the future.

I'm glad you like it!

**Comment by mark-fangzhou-xie** [comment]
Currently, I have to disable this plugin when writing Latex (and re-enable it when writing python). But I believe this plugin has great potential!

Thank you for your reply and for creating this wonderful package!

**Comment by swiknaba** [comment]
Having the same issue with Ruby:

![image](https://user-images.githubusercontent.com/20702503/62068203-dd75b380-b235-11e9-85d2-84a11cd8b0b2.png)

hitting tab expands me
```ruby
  case object
  when condition
    
  end
```
which I use very often to speed-up coding. When enabling TabNine:

![image](https://user-images.githubusercontent.com/20702503/62068264-072eda80-b236-11e9-9925-01d2e9e654dc.png)

autocomplete is gone entirely. So the time-gain through TabNine is more or less lost. If it would be pushed down in the list for e.g. anything that has a higher likelihood than let's say 30% for TabNine, it would be awesome.

Besides, great idea, I'm happy to buy the license when I can use both, TabNine and the atom auto-complete, here a link for the record: https://atom.io/packages/autocomplete-snippets
